# Copyright 2026 Marimo. All rights reserved.
"""Fork branding: the app presents itself as "dedomena" (see FORK.md).

The frontend bundle is prebuilt (npmjs is blocked on the dev machine), so
rebranding happens at the layers we control:

- served HTML (browser tab title, meta tags) — patched server-side here,
  so it survives `scripts/fork_refresh_static.py` asset refreshes;
- icon/manifest files in `marimo/_static` — regenerated by
  `scripts/fork_rebrand_static.py` (run automatically after asset refresh);
- CLI startup/shutdown banners.

Text rendered by the JS bundle itself (menus, dialogs) still says
"marimo"; changing that requires a frontend build on an unblocked network.
"""

from __future__ import annotations

APP_NAME = "dedomena"


def brand_html(html: str) -> str:
    """Rebrand branding-only strings in served HTML.

    Functional attributes (data-marimo, marimo-version, ...) are left
    untouched — the frontend depends on them.
    """
    return html.replace(
        'content="a marimo app"', f'content="a {APP_NAME} app"'
    )
